name: build YAML

on:
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install postgresql
        run: |
          sudo apt install -y postgresql postgresql-contrib

      - name: Run postgresql server
        run: |
          sudo service postgresql start

      - name: Set up database and create user for application
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{secrets.DB}};"
          sudo -u postgres psql -c "CREATE USER ${{secrets.DB_USER}} with password '${{secrets.DB_PASSWORD}}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{secrets.DB}} TO ${{secrets.DB_USER}};"
  

  build_and_test:
    runs-on: ubuntu-latest

    needs: install_dependencies

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and Test Spring boot Application
        run: |
          mvn -version
          mvn clean install