name: build YAML

on:
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install postgresql
        run: |
          sudo apt install -y postgresql postgresql-contrib


  build_and_test:
    runs-on: ubuntu-latest
    env:
      DB: ${{ secrets.DB }}
      HOST: ${{ secrets.HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    needs: install_dependencies

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run postgresql server
        run: |
          sudo touch /var/log/webapp.log
          sudo chmod o+rw /var/log/webapp.log
          sudo service postgresql start

      - name: Set up database and create user for application
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${DB};"
          sudo -u postgres psql -c "CREATE USER ${DB_USER} with password '${DB_PASSWORD}';"
          sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH SUPERUSER;"


      - name: Build and compile code
        run: |
          pg_isready
          mvn -version
          mvn compile

      - name: Run Integration and unit Tests
        run: |
          mvn clean verify